Initial commit for repeaters
Cursed-Solutions/Tanjun pull request #109
Opened 2021-09-26 00:08 UTC by crazygmr101

Draft PR adding an integrated way to add repeating tasks to tanjun.

Based off of https://github.com/FasterSpeeding/Yuyo/pull/29/, but missing some features atm.

2021-09-30 03:46 UTC, FasterSpeeding requested changes

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/abc.py
> +        -------
Leave this off the standard interface for now

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +        /,
callback should be positional only and so should delay

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +    def set_pre_callback(self, callback: CallbackSigT) -> Repeater[CallbackSigT]:
positional only for callback

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +    def set_post_callback(self, callback: CallbackSigT) -> Repeater[CallbackSigT]:
Positional only for callback

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +        self._event_loop = event_loop or asyncio.get_event_loop()
It should bind to the event loop when its started, not when its initialised, also get_running_loop should be use dover get_event_loop

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +        self._max_runs: typing.Optional[int] = max_runs
this type hint is unnecessary as it should be inferred from the variable

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/clients.py
> +                repeater.stop()
These should be internally  managed by the component, plus you also need to start them if a component is added to an already active client

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/components.py
> +    def repeaters(self) -> typing.List[AbstractRepeater]:
this should be typed as returning collections.Sequence

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +    @property
Missing class docstring here

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +CallbackSig = typing.Callable[..., typing.Awaitable[typing.Any]]
Is anything actually done with the result of this callback? Might make more sense to type it as returning None which'd be more inline with stuff like command hooks and what not

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/__init__.py
> +    "repeaters",
Small style thing but the module is usually the first entry, not the last

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +    @property
This class needs slots

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +
missing slots here

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +        except Exception as e:  # noqa - I have to
Could this be a more descriptive comment?

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +CallbackSig = typing.Callable[..., typing.Awaitable[typing.Any]]
collections.Awaitable and collections.Callable should be instead of their deprecated typing counterparts in type hints and doc type sections, seems like you need to fix up some consistency with these

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +        typing.Callable[..., typing.Awaitable[typing.Any]]
You can just put CallbackSig in these doc type sections

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +        self._fatal_exceptions: typing.List[type[Exception]] = []
list instead of typing.List

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +    exceptions : typing.List[type[Exception]]
list not typing.List

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/clients.py
> +                repeater.stop()
I might need to introduce some changes to how components are handled before you'd really be able to implement that well yourself, hope you don't mind waiting a bit for that

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +    def __call__(self, *args: list[typing.Any], **kwargs: dict[typing.Any, typing.Any]):
you need to type the return type here also can we use the style found in commands.py to better type `__call__`
```py
    if typing.TYPE_CHECKING:
        __call__: CallbackSigT

    else:

        async def __call__(self, *args, **kwargs) -> None:
            await self._callback(*args, **kwargs)

```

2021-09-30 03:46 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +            Self
these are usually documented as
```py
Returns
-------
Self
    The repeater instance to enable chained calls.
```

2021-10-26 17:48 UTC, crazygmr101 commented
Resolved all but 1 change, and merged master into the PR

2021-11-15 08:13 UTC, FasterSpeeding commented
Sorry for leaving this pr sitting for so long, i'm going to finish those changes that this requires today and then you can rebase onto that and implement starting up and stopping the repeaters in Component.open and Component.close

2021-11-17 07:39 UTC, FasterSpeeding commented
Looks like you'll need to rebase this but also random question, what do you think about calling these "scheduled callbacks" instead of "repeaters"?

2021-11-17 08:07 UTC, FasterSpeeding requested changes

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +        event_loop: typing.Optional[asyncio.AbstractEventLoop] = None,
event_loop shouldn't be a parameter here, itshould only ever be set by repeater.start()

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +            self._event_loop.create_task(self._post_callback())
stop should unset the event loop.

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +            raise RuntimeError("Repeater already running")
should error if its already running before binding the event loop and there's no need to check `.done()` here

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +        if not self._event_loop:
The start method should take a positional only client arg of type tanjun.injecting.InjectorClient and pass it to `self.loop()`

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +        self._pre_callback: typing.Optional[CallbackSig] = None
these callbacks should be wrapped with `tanjun.injecting.CallbackDescriptor` and called as `descriptor.resolve(ctx)` to enable dependency injection (where `ctx` is an instance of `tanjun.injecting.BasicInjectionContext` which is initiated per-loop and shared between the relevant callbacks).

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +    def start(self) -> asyncio.Task[None]:
this should just keep the task internal

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/clients.py
> +                repeater.stop()
This logic should be moved to Component.open

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/clients.py
> +            for repeater in component.repeaters:  # type: ignore
This logic should be moved to Component.close

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/components.py
> +
There also needs to be remove_repeater method

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/components.py
> +    def add_repeater(self, repeater: AbstractRepeater):
These methods need documentation

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +class Repeater(typing.Generic[CallbackSigT], AbstractRepeater):
need a `as_repeater` decorator method which acts similarly to stuff `as_message_command`/`as_slash_command`

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/repeaters.py
> +    @tanjun.as_repeater(seconds=1)
these examples are how this should look but should also include the `@component.with_repeater` call

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/components.py
> +    def repeaters(self) -> collections.Sequence[AbstractRepeater]:
docs

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/components.py
> +            self._repeaters = [copy.copy(repeater) for repeater in self._repeaters] if self._repeaters else []
repeater should have a "copy" method which is called here rather than using copy.copy

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/components.py
these imports are off standard, should just be importing `from . import repeaters` and accessing these as attributes on `repeaters`

2021-11-17 08:07 UTC, FasterSpeeding commented on tanjun/components.py
> +    ) -> collections.Callable[[CallbackSigT], abc.AbstractRepeater]:
This is off standard for the lib, with_repeater should just take one positional arg of type typeVar(AbstractRepeater) and return it after calling self.add_repeater(repeater) to allow for custom impls

2021-11-23 00:06 UTC, FasterSpeeding commented
Might be helpful to have the repeaters also implement `tanjun.componentsComponentLoader` once this has been rebased

2022-01-01 18:11 UTC, FasterSpeeding commented
I'ma finish this due to inactivity

2022-01-07 15:19 UTC, merged